from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.api.routes import auth, certificates, courses, daily_pulse, explore, lessons, quizzes, sandbox, tracks, users
from app.core.db import Base, engine
from app.models import *  # noqa: F401,F403 -- registers every model with Base.metadata before create_all

app = FastAPI(
    title="Cortex AI",
    description="Interactive AI training platform: role-based tracks, a daily agentic micro-learning pipeline, and an in-browser prompt sandbox.",
    version="0.1.0",
)

# Lesson images generated by app/agents/image_mcp.py -- served from a
# stable local path rather than hotlinking OpenAI's own temporary URLs.
STATIC_DIR = Path(__file__).resolve().parent.parent / "static"
STATIC_DIR.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://cortex.xiox.in"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(users.router)
app.include_router(lessons.router)
app.include_router(daily_pulse.router)
app.include_router(sandbox.router)
app.include_router(explore.router)
app.include_router(tracks.router)
app.include_router(courses.router)
app.include_router(quizzes.router)
app.include_router(certificates.router)


@app.on_event("startup")
def on_startup():
    # SQLite + a small schema: create_all is fine for local dev. Once this
    # needs real migrations (adding a column without dropping data), switch
    # to `alembic upgrade head` here instead -- the alembic/ directory is
    # already scaffolded for that.
    Base.metadata.create_all(bind=engine)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/")
def root():
    """This is an API-only backend -- the actual app UI lives on the Next.js
    frontend (http://localhost:3000 in dev). A bare 404 on `/` here reads as
    "the app is broken" to anyone who lands on this port directly, so this
    exists purely to point them at the right place and at the interactive
    API docs, rather than leaving the root route undefined."""
    return {
        "service": "Cortex AI API",
        "frontend": "http://localhost:3000",
        "docs": "/docs",
        "health": "/health",
    }
